services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    restart: always

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost

    ports:
      - "8180:8080"

    volumes:
      - ./docker/keycloak-data:/opt/keycloak/data